const consultants = [
  {
    id: "1",
    name: "Avery Thompson",
    role: "Full-Stack Engineer",
    location: "Atlanta, GA",
    yearsOfExp: 5,
    skills: ["Vue.js", "Laravel", "AWS"],
    bio: "Experienced in developing end-to-end web applications with a focus on performance.",
  },
  {
    id: "2",
    name: "Blake Rogers",
    role: "Frontend Engineer",
    location: "Chicago, IL",
    yearsOfExp: 3,
    skills: ["Angular", "TypeScript", "SCSS"],
    bio: "Builds responsive, mobile-first user interfaces with a strong emphasis on accessibility.",
  },
  {
    id: "3",
    name: "Carmen Diaz",
    role: "Backend Engineer",
    location: "Boston, MA",
    yearsOfExp: 9,
    skills: ["Django", "PostgreSQL", "Docker"],
    bio: "Specializes in scalable, secure REST APIs and containerized deployments.",
  },
  {
    id: "4",
    name: "Diego Patel",
    role: "DevOps Engineer",
    location: "Denver, CO",
    yearsOfExp: 4,
    skills: ["GCP", "Terraform", "Jenkins"],
    bio: "Implements infrastructure-as-code solutions and automates CI/CD pipelines.",
  },
  {
    id: "5",
    name: "Elena Martinez",
    role: "Data Scientist",
    location: "Seattle, WA",
    yearsOfExp: 6,
    skills: ["R", "SQL", "scikit-learn"],
    bio: "Develops predictive models and dashboards to inform business decisions.",
  },
  {
    id: "6",
    name: "Felix Nguyen",
    role: "Mobile Developer",
    location: "Austin, TX",
    yearsOfExp: 7,
    skills: ["Kotlin", "Android", "Firebase"],
    bio: "Creates performant native Android applications with clean architecture.",
  },
  {
    id: "7",
    name: "Giselle Kim",
    role: "UI/UX Designer",
    location: "Portland, OR",
    yearsOfExp: 2,
    skills: ["Figma", "Adobe XD", "Illustrator"],
    bio: "Designs intuitive prototypes and conducts user research for web and mobile.",
  },
  {
    id: "8",
    name: "Harold Singh",
    role: "Cloud Engineer",
    location: "Miami, FL",
    yearsOfExp: 8,
    skills: ["Azure", "Docker", "Kubernetes"],
    bio: "Architects cloud-native solutions and optimizes resource utilization.",
  },
  {
    id: "9",
    name: "Iris Chen",
    role: "Machine Learning Engineer",
    location: "Palo Alto, CA",
    yearsOfExp: 5,
    skills: ["TensorFlow", "Python", "Keras"],
    bio: "Deploys computer vision and NLP models to production environments.",
  },
  {
    id: "10",
    name: "Jordan Baker",
    role: "Security Engineer",
    location: "New York, NY",
    yearsOfExp: 10,
    skills: ["Network Security", "Penetration Testing", "Splunk"],
    bio: "Ensures infrastructure and application security through audits and code reviews.",
  },
  {
    id: "11",
    name: "Kaiden Brooks",
    role: "Full-Stack Engineer",
    location: "Los Angeles, CA",
    yearsOfExp: 6,
    skills: ["React", "Express", "MongoDB"],
    bio: "Builds MERN-stack applications with real-time features and microservices.",
  },
  {
    id: "12",
    name: "Lola Patterson",
    role: "Frontend Engineer",
    location: "San Diego, CA",
    yearsOfExp: 4,
    skills: ["Svelte", "CSS", "Webpack"],
    bio: "Creates blazing-fast SPAs using modern JavaScript frameworks.",
  },
  {
    id: "13",
    name: "Malik Herrera",
    role: "Backend Engineer",
    location: "Houston, TX",
    yearsOfExp: 3,
    skills: ["Ruby on Rails", "MySQL", "Redis"],
    bio: "Develops robust APIs and implements background job processing.",
  },
  {
    id: "14",
    name: "Nina O'Connor",
    role: "DevOps Engineer",
    location: "Phoenix, AZ",
    yearsOfExp: 5,
    skills: ["AWS", "Ansible", "Docker"],
    bio: "Automates server provisioning and maintains high-availability architectures.",
  },
  {
    id: "15",
    name: "Omar Johnson",
    role: "Data Scientist",
    location: "Philadelphia, PA",
    yearsOfExp: 7,
    skills: ["Python", "Pandas", "Tableau"],
    bio: "Creates data visualizations and builds statistical models for forecasting.",
  },
  {
    id: "16",
    name: "Priya Verma",
    role: "Mobile Developer",
    location: "Dallas, TX",
    yearsOfExp: 2,
    skills: ["Flutter", "Dart", "GraphQL"],
    bio: "Designs cross-platform mobile applications with smooth animations.",
  },
  {
    id: "17",
    name: "Quentin Miles",
    role: "UI/UX Designer",
    location: "Charlotte, NC",
    yearsOfExp: 4,
    skills: ["Sketch", "InVision", "HTML/CSS"],
    bio: "Develops wireframes and conducts usability testing for enterprise apps.",
  },
  {
    id: "18",
    name: "Rebecca Liu",
    role: "Cloud Engineer",
    location: "San Jose, CA",
    yearsOfExp: 9,
    skills: ["AWS", "Terraform", "Linux"],
    bio: "Designs scalable microservices architectures and enforces security best practices.",
  },
  {
    id: "19",
    name: "Samuel Grant",
    role: "Machine Learning Engineer",
    location: "Boulder, CO",
    yearsOfExp: 6,
    skills: ["PyTorch", "C++", "SQL"],
    bio: "Implements deep learning models with a focus on performance optimization.",
  },
  {
    id: "20",
    name: "Talia Rivera",
    role: "Security Engineer",
    location: "Washington, DC",
    yearsOfExp: 8,
    skills: ["SIEM", "IAM", "Vulnerability Assessment"],
    bio: "Conducts penetration tests and develops secure authentication flows.",
  },
  {
    id: "21",
    name: "Usha Desai",
    role: "Full-Stack Engineer",
    location: "Minneapolis, MN",
    yearsOfExp: 7,
    skills: ["Next.js", "Node.js", "PostgreSQL"],
    bio: "Builds SEO-friendly web applications and real-time data dashboards.",
  },
  {
    id: "22",
    name: "Victor Hugo",
    role: "Frontend Engineer",
    location: "Nashville, TN",
    yearsOfExp: 5,
    skills: ["React", "Redux", "CSS Modules"],
    bio: "Focuses on component-driven development and performant state management.",
  },
  {
    id: "23",
    name: "Wendy Cho",
    role: "Backend Engineer",
    location: "Columbus, OH",
    yearsOfExp: 4,
    skills: ["Spring Boot", "Java", "MySQL"],
    bio: "Implements microservices with robust authentication and transaction support.",
  },
  {
    id: "24",
    name: "Xavier Bell",
    role: "DevOps Engineer",
    location: "Salt Lake City, UT",
    yearsOfExp: 3,
    skills: ["Docker", "Kubernetes", "Helm"],
    bio: "Manages container orchestration and streamlines release cycles.",
  },
  {
    id: "25",
    name: "Yvonne Harris",
    role: "Data Scientist",
    location: "Orlando, FL",
    yearsOfExp: 8,
    skills: ["Scala", "Spark", "Hadoop"],
    bio: "Processes large datasets and builds ETL pipelines for big data analytics.",
  },
  {
    id: "26",
    name: "Zachary Young",
    role: "Mobile Developer",
    location: "Indianapolis, IN",
    yearsOfExp: 6,
    skills: ["Swift", "iOS", "Core Data"],
    bio: "Develops native iOS apps with offline caching and push notifications.",
  },
  {
    id: "27",
    name: "Alicia Gomez",
    role: "UI/UX Designer",
    location: "Las Vegas, NV",
    yearsOfExp: 3,
    skills: ["Adobe XD", "Photoshop", "CSS"],
    bio: "Creates high-fidelity prototypes and conducts A/B testing to refine designs.",
  },
  {
    id: "28",
    name: "Brandon Lee",
    role: "Cloud Engineer",
    location: "Detroit, MI",
    yearsOfExp: 5,
    skills: ["Google Cloud", "Terraform", "Linux"],
    bio: "Implements cost-effective cloud solutions and ensures disaster recovery strategies.",
  },
  {
    id: "29",
    name: "Cecilia Ford",
    role: "Machine Learning Engineer",
    location: "Milwaukee, WI",
    yearsOfExp: 4,
    skills: ["R", "MLlib", "SQL"],
    bio: "Builds recommendation engines and clustering models for user segmentation.",
  },
  {
    id: "30",
    name: "Dominic Ruiz",
    role: "Security Engineer",
    location: "Cincinnati, OH",
    yearsOfExp: 7,
    skills: ["Firewalls", "IDS/IPS", "Risk Assessment"],
    bio: "Analyzes threat vectors and implements network hardening practices.",
  },
  {
    id: "31",
    name: "Emilia Novak",
    role: "Full-Stack Engineer",
    location: "Jacksonville, FL",
    yearsOfExp: 2,
    skills: ["MEAN Stack", "TypeScript", "NGINX"],
    bio: "Rapidly prototypes MVPs using modern JavaScript frameworks and reverse proxies.",
  },
  {
    id: "32",
    name: "Finn O'Neil",
    role: "Frontend Engineer",
    location: "Memphis, TN",
    yearsOfExp: 6,
    skills: ["Vue.js", "Vuetify", "Sass"],
    bio: "Delivers pixel-perfect UIs and optimizes bundle sizes for fast load times.",
  },
  {
    id: "33",
    name: "Gabriela Santos",
    role: "Backend Engineer",
    location: "Oklahoma City, OK",
    yearsOfExp: 8,
    skills: ["PHP", "Laravel", "MySQL"],
    bio: "Develops modular APIs and implements unit testing for robust services.",
  },
  {
    id: "34",
    name: "Hector Alvarez",
    role: "DevOps Engineer",
    location: "Louisville, KY",
    yearsOfExp: 5,
    skills: ["Azure", "CI/CD", "Terraform"],
    bio: "Configures cloud pipelines and monitors system performance metrics.",
  },
  {
    id: "35",
    name: "Ingrid Berg",
    role: "Data Scientist",
    location: "Richmond, VA",
    yearsOfExp: 3,
    skills: ["Python", "TensorFlow", "Pandas"],
    bio: "Designs neural network architectures for image recognition projects.",
  },
  {
    id: "36",
    name: "Jake Wilson",
    role: "Mobile Developer",
    location: "Providence, RI",
    yearsOfExp: 4,
    skills: ["React Native", "Java", "SQLite"],
    bio: "Creates hybrid mobile apps with seamless native integrations.",
  },
  {
    id: "37",
    name: "Kiara Patel",
    role: "UI/UX Designer",
    location: "Fresno, CA",
    yearsOfExp: 7,
    skills: ["Sketch", "Figma", "Prototyping"],
    bio: "Leads user research sessions and translates findings into design improvements.",
  },
  {
    id: "38",
    name: "Leo Zhang",
    role: "Cloud Engineer",
    location: "Omaha, NE",
    yearsOfExp: 2,
    skills: ["AWS", "Docker", "CloudFormation"],
    bio: "Automates cloud deployments and maintains IaC templates for consistency.",
  },
  {
    id: "39",
    name: "Maya Thompson",
    role: "Machine Learning Engineer",
    location: "New Orleans, LA",
    yearsOfExp: 9,
    skills: ["PyTorch", "Python", "Kafka"],
    bio: "Implements real-time data processing pipelines and deep learning workflows.",
  },
  {
    id: "40",
    name: "Noah Fischer",
    role: "Security Engineer",
    location: "Honolulu, HI",
    yearsOfExp: 5,
    skills: ["Penetration Testing", "Wireshark", "Linux"],
    bio: "Conducts wireless security audits and hardens Linux-based systems.",
  },
  {
    id: "41",
    name: "Olivia Carter",
    role: "Full-Stack Engineer",
    location: "Tampa, FL",
    yearsOfExp: 4,
    skills: ["Django", "React", "PostgreSQL"],
    bio: "Combines Python backends with modern frontends to deliver maintainable apps.",
  },
  {
    id: "42",
    name: "Parker Adams",
    role: "Frontend Engineer",
    location: "Anchorage, AK",
    yearsOfExp: 3,
    skills: ["Svelte", "CSS", "TypeScript"],
    bio: "Prioritizes minimal bundle sizes and fast hydration for edge deployments.",
  },
  {
    id: "43",
    name: "Quinn Rivera",
    role: "Backend Engineer",
    location: "Des Moines, IA",
    yearsOfExp: 6,
    skills: ["Go", "PostgreSQL", "Docker"],
    bio: "Writes high-performance microservices and designs efficient database schemas.",
  },
  {
    id: "44",
    name: "Riley Kim",
    role: "DevOps Engineer",
    location: "Boise, ID",
    yearsOfExp: 8,
    skills: ["Kubernetes", "AWS", "Jenkins"],
    bio: "Creates self-healing clusters and manages blue-green deployment strategies.",
  },
  {
    id: "45",
    name: "Sophia Martinez",
    role: "Data Scientist",
    location: "Little Rock, AR",
    yearsOfExp: 5,
    skills: ["R", "ggplot2", "SQL"],
    bio: "Performs exploratory data analysis and crafts visual dashboards for stakeholders.",
  },
  {
    id: "46",
    name: "Tyler Brooks",
    role: "Mobile Developer",
    location: "Newark, NJ",
    yearsOfExp: 7,
    skills: ["Kotlin", "Android", "Retrofit"],
    bio: "Specializes in offline-first Android apps with efficient network handling.",
  },
  {
    id: "47",
    name: "Ursula Johnson",
    role: "UI/UX Designer",
    location: "Birmingham, AL",
    yearsOfExp: 2,
    skills: ["Figma", "Photoshop", "InVision"],
    bio: "Delivers polished mockups and collaborates closely with product teams.",
  },
  {
    id: "48",
    name: "Victor Chen",
    role: "Cloud Engineer",
    location: "Buffalo, NY",
    yearsOfExp: 6,
    skills: ["Azure", "Ansible", "Docker"],
    bio: "Implements secure cloud architectures and automates configuration management.",
  },
  {
    id: "49",
    name: "Willow Turner",
    role: "Machine Learning Engineer",
    location: "Reno, NV",
    yearsOfExp: 3,
    skills: ["Scikit-learn", "Python", "NumPy"],
    bio: "Builds prototype ML models and assists with data preprocessing workflows.",
  },
  {
    id: "50",
    name: "Xavier Lopez",
    role: "Security Engineer",
    location: "Rochester, NY",
    yearsOfExp: 9,
    skills: ["Network Security", "SIEM", "Penetration Testing"],
    bio: "Leads security incident response and develops enterprise-wide security policies.",
  },
];

export default consultants;
